### ISSUE TITLE
Doesn't output HTML Code

### ISSUE THREAD

**Issue by wuwx** [woods/gravatar-plugin#4]
when i use this plugin, view code like this:

<%= gravatar_for @user %>

html has been escaped .....

i'm using rails 3.1.3

**Comment by woods** [comment]
Are you referring to the ampersand in the middle of the source URL being escaped with `&amp;`? 

```
<img class="gravatar" alt="" width="50" height="50" src="http://www.gravatar.com/avatar/f5dfb241dbb07b9709e0c44e08318a98?rating=PG&amp;size=50" />
```

That would be correct escaping: 

http://htmlhelp.com/tools/validator/problems.html#amp

Let me know if it's some other problem.

**Comment by woods** [comment]
Ahh, actually, I bet it's because rails 3 is automatically escaping _all_ the HTML. 

Try this instead and see if it fixes the problem temporarily:

```
<%= raw gravatar_for @user %>
```

**Comment by wuwx** [comment]
oh, yeah, i use <%= raw gravatar_for @user %>, then rails work OK now
thank you
